### ISSUE TITLE
Submodules

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#115]
I am wonder if that should be https link instead of git?

```
[submodule "config/base16-shell"]
	path = config/base16-shell
	url = git@github.com:chriskempson/base16-shell.git
```

**Comment by nicknisi** [comment]
I'm actually experimenting with removing the submodule entirely and instead managing it with a simple plugin manager script. Testing it [here](https://github.com/nicknisi/dotfiles/commit/e2ab45a3358a90d542a3b29f8059b245f02b8ed8)

**Comment by nicknisi** [comment]
I went ahead and merged this, along with some other fixes. For now, you'll have to re-run `install/link.sh` so that the .zshenv file gets properly symlinked.

On the first run, zsh-autosuggestions, zsh-syntax-highlighting, and base16-shell will all be automatically downloaded. These can then be manually updated by running `zfetch update`. Thanks again!

**Comment by jrock2004** [comment]
@nicknisi so with these new changes, I removed from `~/.config/base16shell` as you are using the new zfetch. But not colors seem off

**Comment by jrock2004** [comment]
Might be hard to see 

![image](https://user-images.githubusercontent.com/655716/64198942-41a01e80-ce57-11e9-9901-9affba15fb84.png)

**Comment by nicknisi** [comment]
hmm, yeah that does seem off. What theme from base16 are you using? Is `$BASE16_THEME` set?

**Comment by jrock2004** [comment]
Its empty

![image](https://user-images.githubusercontent.com/655716/64208071-02c89380-ce6c-11e9-8028-eb30dcb92bd4.png)

**Comment by jrock2004** [comment]
I notice that in your configs its not set. I guess I never really looked to see how you were setting the theme for ZSH

**Comment by jrock2004** [comment]
Should I open as a new issue?

**Comment by nicknisi** [comment]
I reopened this one to continue the discussion. So, I don't actually set that anywhere in the dot files because it's something I end up changing often enough that it'd be annoying to have it. This is getting set by manually running one of the base16 commands (`base16_ashes`) for example.

Do those commands still exist on your setup? 

![image](https://user-images.githubusercontent.com/293805/64266895-03f4d180-cefb-11e9-9d31-4ac16b2b7373.png)

**Comment by jrock2004** [comment]
I do have that command. I set the theme and now it looks better

**Comment by jrock2004** [comment]
Would I just add `export BASE16_THEME='default-dark'` to set the theme I want?

**Comment by nicknisi** [comment]
Running a command like `base16_default-dark` should create a symlink to that theme in your home directory called `~/.base16_theme`. The file sourced [here](https://github.com/nicknisi/dotfiles/blob/f653cfcad252a768d62c567832f6cb34871181e6/zsh/zshrc.symlink#L44) will use this to load the theme you want going forward.

![image](https://user-images.githubusercontent.com/293805/64268233-53d49800-cefd-11e9-9c5f-ee9ba29c5301.png)

**Comment by nicknisi** [comment]
Here's where this is happening in base16-shell https://github.com/chriskempson/base16-shell/blob/ce8e1e540367ea83cc3e01eec7b2a11783b3f9e1/profile_helper.sh#L11-L15
