### ISSUE TITLE
Mac Terminal vs iterm2

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#13]
So I notice that default mac terminal looks way blue that what iterm does. Not sure why iterm is adding that grey or maybe it should. Any ideas?

<img width="1273" alt="screen shot 2015-11-09 at 10 40 00 pm" src="https://cloud.githubusercontent.com/assets/655716/11053863/ec8b7b2a-8732-11e5-9f5f-aa357a4b240a.png">

**Comment by nicknisi** [comment]
Thanks for the feedback! The reason that the colorscheme is messed up in terminal.app is because Terminal.app doesn't support setting the terminal colors from the shell scripts in [base16-shell](https://github.com/chriskempson/base16-shell). We can correct this, however, by generating a colorscheme using [base16-builder](https://github.com/chriskempson/base16-builder). To do this, clone the repository and then run the following command

```shell
./base16 -s schemes/chalk.yml
```

This threw an error when I tried it the first time because of the `dmenu` template, so I removed that directory (`templates/dmenu`) temporarily and then tried again and it worked. The file you're looking for from this output is in `output/terminal-app/base16-chalk.dark.terminal`. Double-clicking on this file will load the necessary color s for Terminal.app.

Next, you'll want to remove the following line from the vimrc and then you should be good to go.

```vim
let base16colorspace=256  " Access colors present in 256 colorspace"
```

[Here](http://d.pr/f/emCv) is a link to a generated `base16-chalk.dark.terminal` file I was able to generate. Using the instructions above, you can also generate color schemes for other base16 themes, or jus switch to a different colorscheme in vim. Please let me know if you have any other questions. Thanks!
![screen shot 2015-11-11 at 11 40 22 pm](https://cloud.githubusercontent.com/assets/293805/11111332/bb6cf72a-88cd-11e5-8640-eea75aed8a8c.png)
