### ISSUE TITLE
Keep having issue with git/hooks/post-checkout

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#149]
Every time I clone a repository I get an error:

`.git/hooks/post-checkout: 17: .git/hooks/post-checkout: [[: not found`

it goes away if I delete the file post-checkout.

**Comment by nicknisi** [comment]
Hmm, I have not been seeing this. Is the shebang in post-checkout `#!/usr/bin/env bash` for you?

**Comment by nicknisi** [comment]
Closing since I haven't heard back. Let me know if you're still having issues.

**Comment by ajr-dev** [comment]
git commit                                                                                                                                                 + master
.git/hooks/pre-commit: 9: shopt: not found

Executing /home/user/.dotfiles/git/hooks/*.pre-commit
.git/hooks/pre-commit: 13: /home/user/.dotfiles/git/hooks/*.pre-commit: not found
.git/hooks/pre-commit: 17: [[: not found

**Comment by nicknisi** [comment]
The hooks effectively get copied to your local repository every time you clone or init a repo. This configuration is managed in the `~/.gitconfig`. Remove this line if you don't want them. https://github.com/nicknisi/dotfiles/blob/8d03b744b9e0f0e6cf62bcfa0d7aab1a9a96a34c/git/gitconfig.symlink#L8

Additionally, if the problem is persisting in already cloned / init'd repos, it's because the hooks exist as an independent copy within each. you can `rm -rf .git/hooks` to remove them, and then run `git init` again to re-add the correct ones.

**Comment by ajr-dev** [comment]
I still have trouble with this every time I clone your repository. And with every plugin zplug installs I get the same error too.
What should I see when I execute `/usr/bin/env`?
