### ISSUE TITLE
I'm not seeing coc diagnostic signs.

### ISSUE THREAD

**Issue by ajr-dev** [nicknisi/dotfiles#181]
Maybe I'm missing fonts or something. I'm using FiraCode Nerd Font. https://i.stack.imgur.com/7bIhp.png

**Comment by nicknisi** [comment]
Hmm, that could be. Just to confirm, this is based off the `master` branch, right? There is also a [`lua-neovim-lsp`](https://github.com/nicknisi/dotfiles/tree/lua-neovim-lsp) branch that is very much a work in progress that removes coc completely.

**Comment by ajr-dev** [comment]
It is the master branch. I will try with some other patched font. What does it have to show?

**Comment by nicknisi** [comment]
actually, thinking back to it, it's set up to show thin, colored lines for adding, removing, or modifying lines of a file. I don't believe you should need any special fonts for this.

![Uploading CleanShot 2021-06-30 at 20.41.15.png…]()

I asked about the other branch because I was seeing similar, thick lines when switching over to that, but that doesn't seem to be happening for me on that branch anymore, either.

**Comment by ajr-dev** [comment]
So just to be sure,  I should be checking the coc documentation to make sure I have everything it needs?

**Comment by nicknisi** [comment]
These symbols are configured here: https://github.com/nicknisi/dotfiles/blob/e71df91d6432bb6f203daf9e8c700dfc984e2b7f/config/nvim/coc-settings.json#L4-L7

**Comment by nicknisi** [comment]
Closing this as I've removed coc as a dependency in favor of the native Neovim LSP in #190.
