### ISSUE TITLE
Wrong 'if' statement in brew.sh

### ISSUE THREAD

**Issue by tommyc38** [nicknisi/dotfiles#34]
Here are your first few line:
```bash
if test ! $(which brew); then
    echo "Installing homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi
```

This statement will always ring true because the output will always be a a non null string.  For example, if you replaced 'which brew' with 'which foo', it will still evaluate to true because the output returns a non null string "foo not found".  You should use `if [-e $(which brew) ]` instead so it doesn't try and install it if it's already installed.

**Comment by tommyc38** [comment]
sorry...  It should be `if [ -e "$(which brew)" ]`.  There must be a space between `[` and `-e`. Second, it needs to be wrapped in quotes so it doesn't expand the output into multiple string arguments for each word separated by spaces (e.g. "foo" , "not", "found".

**Comment by nicknisi** [comment]
@tommyc38 Thanks for the tip. However, I looked deeper into this, and because I'm using `test` and `$(which brew)` has an exist status of `0` when it exists and `1` when it doesn't, it should still work. To demonstrate this further, I created a test script with output checking for both `brew` and a nonexistent `nonexistent` script. In both cases, the output is what I'd expect (lower left of screenshot). Looking at the output in the lower right, I can see that the exit status is `0` when the command exists and `1` otherwise.

<img width="1066" alt="screen shot 2016-09-19 at 11 10 22 pm" src="https://cloud.githubusercontent.com/assets/293805/18657327/b2436c8c-7ebe-11e6-89ea-9feafbb1f2f8.png">

I'm going to close this for now, but please let me know if there is something I'm missing. Thanks!

**Comment by tommyc38** [comment]
Thanks for the response!  You are correct, your script runs as expected.  However, I have a few things that I don't understand (my question posted below).  I am a newbie and kicking things off with Linux, Bash scripting, and Vim.  Loved your videos and gleaned a lot from your dotfiles...thank you!!!  

http://stackoverflow.com/questions/39606995/default-test-expression-behaves-different-in-zsh-vs-bash-why
