### ISSUE TITLE
Leader t gfiles

### ISSUE THREAD

**Issue by jrock2004** [nicknisi/dotfiles#41]
So I like in your config you have decided to use gfiles for searching for a file to edit, but I have noticed an issue that when I create a new file that has not been committed yet, Gfiles wont see it. So how do you get around this? I have been just doing `:FZF` but then that gets ugly cause then it loads the search with all the node and bower component stuff.

Just interested how you get around this

**Comment by nicknisi** [comment]
Currently, I have `<leader>e` mapped to use fzf to search all files. However, You can also [setup fzf](https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore) to use something like `ag -g` instead of `find`, which understands .gitignore files! To do this, add `export FZF_DEFAULT_COMMAND='ag -g ""'` to your ~/.zshrc.
