### ISSUE TITLE
what are the controls for nerdtree

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#47]
I couldn't figure out the controls for nerdtree in vim. Also what if I want to change the controls. Which file has those shortcuts setup?

**Comment by nerdpad** [comment]
@AbhimanyuAryan 

The leader is mapped to ```,```, unless you have changed it.

```<leader>k``` -> Toggle NerdTree

Mapping is in nvim's init.vim file https://github.com/nicknisi/dotfiles/blob/master/config/nvim/init.vim#L258

**Comment by nicknisi** [comment]
In addition to what @nerdpad pointed out, there is also `<leader>y`, which opens NERDTree to the current file. These are the only mappings I have. See https://github.com/scrooloose/nerdtree/blob/master/doc/NERD_tree.txt for what's possible.

**Comment by AbhimanyuAryan** [comment]
someone please tell how to enable nerdtree in vim. How to switch windows, close nerdtree etc @nicknisi @nerdpad

**Comment by nerdpad** [comment]
@AbhimanyuAryan 
`<leader>k` -> open/close NerdTree
`CTRL-W-W` -> switch between vim windows

Also if you want to open NerdTree for all tabs, so that when u switch tabs NerdTree stays open then install the [NerdTreeTabs](https://github.com/jistr/vim-nerdtree-tabs) plugin and change the `<leader>k` and `<leader>y` shortcuts to use NerdTreeTab plugin.

Plugin config for NerdTreeTab: https://github.com/nerdpad/dotfiles/blob/master/config/nvim/plugins.vim#L29
NerdTree config for NerdTreeTab: https://github.com/nerdpad/dotfiles/blob/master/config/nvim/init.vim#L311
