### ISSUE TITLE
how to install vim with python

### ISSUE THREAD

**Issue by AbhimanyuAryan** [nicknisi/dotfiles#70]
hi @nicknisi I'm using your dotfile configuration but I want to use few plugins: 

1. OmniSharp: https://github.com/OmniSharp/omnisharp-vim
2. YouCompleteMe: https://github.com/Valloric/YouCompleteMe
3. Syntactic: https://github.com/vim-syntastic/syntastic

But I get the following errors. I can build vim with python & brew `brew install vim --without-python --with-python3`

but your dotfile is using nvim & all the plugins. I want you dotfile and still want to fix the below error. Please help :)

```
❯ nvim
Error detected while processing /Users/abhimanyuaryan/.dotfiles/config/nvim/plugged/omnisharp-vim/plugin/OmniSharp.vim:
line    8:
Error: OmniSharp requires Vim compiled with +python
YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support.
Error detected while processing /Users/abhimanyuaryan/.dotfiles/config/nvim/plugged/ale/after/plugin/ale.vim:
line   28:
E605: Exception not caught: ALE conflicts with Syntastic. Uninstall it, or disable this warning with `let g:ale_emit_conflict_warnings = 0` in your vimrc file, *before* plugins are loaded.
Press ENTER or type command to continue
```

**Comment by nicknisi** [comment]
To get python working, check out this [FAQ](https://github.com/neovim/neovim/wiki/FAQ#python-support-isnt-working).

As for the errors about Syntastic and ALE, it's because I am using [ALE](https://github.com/w0rp/ale) which does pretty much the same thing as syntastic, but it does it as you type instead of when you save. If you'd rather use syntastic, you can make the following change in *config/nvim/plugins.vim*:

```diff
- Plug 'w0rp/ale' " Asynchonous linting engine
+ Plug 'vim-syntastic/syntastic'
```

Then, restart vim and run `:PlugInstall` to install syntastic and use it instead of ALE.
